/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public String getGreeting() {
        return "Hello world.";
    }
    public String 집가자() {
        
        return "gogo";
    }
 
    
    public String 고등어() {
        return "go등어";
    }
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        int i=1;
        while(i<=100000) {
            System.out.println(i);
            i++;
           
            
        }
    }
}
