/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }
<<<<<<< HEAD
    
    public int add(int a, int b) {
        return a+b;
    }

=======
    public String 집가자() {
        return "gogo";
    }
    
>>>>>>> branch 'master' of https://github.com/carryyun/java110-team-project.git
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
<<<<<<< HEAD
        System.out.println(new App().add(5,7));
=======
      System.out.println("내가더다 ㄹ미ㅏ얼미ㅏ얼미다ㅓㄹㅁ;ㅣㅏ럼;ㅣㅏㅓㄹ;ㅣ마ㅜㄹ미ㅏ처ㅜㅁ리ㅏ처물차ㅣ.머ㅜ치러미차더ㅜ미차ㅓ둠처ㅗ러뫃러ㅗㅁ륭ㄹ미ㅏㅓ오리마ㅓㄷㄹㅁ러믿두두둠");
      System.out.println("두둠칫 ");
>>>>>>> branch 'master' of https://github.com/carryyun/java110-team-project.git
    }
    
   
}
